### ISSUE TITLE
Vim highlights (like in comments and spelling) often have very low constrast

### ISSUE THREAD

**Issue by Iambecomeroot** [dylanaraps/wal#49]
When using the vim theme, comments with special highlighted words or incorrectly spelled words with `set spell` have very little contrast. Here is a screenshot of what I mean.
![image](https://user-images.githubusercontent.com/8503756/26895400-d9ffd5f2-4b97-11e7-8bf3-f713e5faf105.png)
On the left, the word `NOTE` is completely unreadable and on the right the unknown word `ISO8601` is sort of legible but it doesn't really feel like it fits the theme.

I just pulled from master (commit `800837bd0399bc8463e4c4079613d44ce58f5964 `) and updated my vim plugins.

**Comment by dylanaraps** [comment]
I've fixed the first issue (`NOTE`/`TODO`) highlighting. I can't reproduce the second issue as vim isn't highlighting `ISO8601` like in your screenshot.

Are you able to add this mapping to your `.vimrc`? The mapping will tell you the highlight group I need to modify to fix the issue.

```viml
" Shows the highlight group of whatever's under the cursor
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```

Once I have the highlight group I can fix it. :)

**Comment by Iambecomeroot** [comment]
Its the spell checker. `ISO8601` isn't in the english dictionary so it shows up as a misspelled word. To show misspelled words, you have to do `set spell`. I just picked that word because it was right next to a `NOTE` in a file I had open anyways but just writing gibberish should trigger the effect.
![image](https://user-images.githubusercontent.com/8503756/26908391-bd808244-4bd0-11e7-9b21-d10c82a85055.png)

**Comment by dylanaraps** [comment]
Try the latest master and let me know how it looks now.

**Comment by Iambecomeroot** [comment]
That's awesome. Thanks a bunch.

**Comment by Iambecomeroot** [comment]
I am still getting the weird highlighting in HTML and markdown headings. I used your keybinding to show the highlight group.

![image](https://user-images.githubusercontent.com/8503756/26931507-1f222e56-4c37-11e7-869f-9dd0e3787aed.png)
![image](https://user-images.githubusercontent.com/8503756/26931573-536fa1ca-4c37-11e7-8757-f3a5168a3a45.png)

**Comment by dylanaraps** [comment]
Fixed!

Let me know if you find any other highlighting bugs :)
